name: CI Pipeline

on:
  push: # Trigger on all pushes to any branch
    branches: 
      - '**' # Match all branches
  pull_request: # Trigger on all pull requests to any branch
    branches: 
      - '**' # Match all branches


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Run Jest tests
      - name: Run Jest tests
        run: npm test

  detox-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      # Install Java 17 (required for Gradle)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Android SDK & Emulator dependencies
      - name: Set up Android environment
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk adb
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      # Install and start an Android emulator
      - name: Set up Android Emulator
        run: |
          sdkmanager --install "system-images;android-30;default;x86_64"
          sdkmanager --install "platforms;android-30"
          sdkmanager --install "platform-tools"
          sdkmanager --install "emulator"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64" --device "pixel"
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu off &

      # Wait for emulator to be ready
      - name: Wait for emulator to start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

      # Build app for Detox
      - name: Build app for Detox
        run: npm run detox-build

      # Run Detox tests
      - name: Run Detox tests
        run: npm run detox-test