name: CI Pipeline

on:
  push: # Trigger on all pushes to any branch
    branches: 
      - '**' # Match all branches
  pull_request: # Trigger on all pull requests to any branch
    branches: 
      - '**' # Match all branches


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Run Jest tests
        run: npm test

  detox-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
          unzip commandlinetools-linux-8092744_latest.zip
          rm commandlinetools-linux-8092744_latest.zip
          yes | ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;default;x86_64" "emulator"
          echo "y" | ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "system-images;android-30;default;x86_64"
          echo "y" | ./cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "emulator"
          echo "no" | ./cmdline-tools/bin/avdmanager create avd -n Pixel_3a_API_30 -k "system-images;android-30;default;x86_64" -d "pixel_3a"

      - name: Set Android environment variables
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/tools/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Start Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd Pixel_3a_API_30 -no-window -no-audio -no-boot-anim -gpu off &
          $ANDROID_HOME/platform-tools/adb wait-for-device
          $ANDROID_HOME/platform-tools/adb shell input keyevent 82

      - name: Verify Emulator
        run: |
          $ANDROID_HOME/platform-tools/adb devices

      - run: npm ci

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x android/gradlew

      - name: Build app for Detox
        run: npm run detox-build

      - name: Run Detox tests
        run: npm run detox-test
