name: CI Pipeline

on:
  push: # Trigger on all pushes to any branch
    branches: 
      - '**' # Match all branches
  pull_request: # Trigger on all pull requests to any branch
    branches: 
      - '**' # Match all branches

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Run Jest tests
        run: npm test

  maestro-tests:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Setup Node.js        
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
  
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Install Maestro CLI
        run: |
          curl -s https://raw.githubusercontent.com/maestro-dev/maestro/master/install.sh | bash
          export PATH=$PATH:$(pwd)/.maestro-cli
  
      - name: Npm install
        run: npm install
        
  
      - name: Start Metro Server
        run: nohup npm start > metro.log 2>&1 &\

      - name: Run Maestro tests
        run: |
          maestro test --device "Pixel 3" --project ./e2e/test.yaml
  
      - name: Upload Test Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-android-artifacts
          path: artifacts
          retention-days: 5
  
  
