name: CI Pipeline

on:
  push: # Trigger on all pushes to any branch
    branches: 
      - '**' # Match all branches
  pull_request: # Trigger on all pull requests to any branch
    branches: 
      - '**' # Match all branches

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Run Jest tests
        run: npm test

  detox-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
  
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
  
      - name: Setup Node.js        
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
  
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
  
      - name: Npm install
        run: npm install
        
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          version: '7.4'  # specify the desired Gradle version
          distribution: 'bin' 

      - name: Make gradlew executable
        run: chmod +x android/gradlew
  
      - name: Build Detox
        run: npm run detox-build
  
      - name: Start Metro Server
        run: npm run detox:start &

      - name: Install libpulse
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse0
  
      - name: Run Detox tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          avd-name: Android_API31
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-metrics
          disable-animations: false
          script: npm run detox-test

      - name: Stop Emulator
        if: always()  # Ensures this runs even if previous steps fail
        run: adb -s emulator-5554 emu kill
  
      - name: Upload Test Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detox-android-artifacts
          path: artifacts
          retention-days: 5
  
