name: CI Pipeline

on:
  push: # Trigger on all pushes to any branch
    branches: 
      - '**' # Match all branches
  pull_request: # Trigger on all pull requests to any branch
    branches: 
      - '**' # Match all branches


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Run Jest tests
        run: npm test

  detox-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK & Emulator
        run: |
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
      
          # Install missing SDK tools
          if [ ! -f "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            echo "Installing missing command-line tools..."
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
            curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip -q sdk-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
            rm sdk-tools.zip
          fi
      
          # Accept licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
      
          # Install necessary Android components
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator" "system-images;android-29;google_apis;x86"
      
      - name: Create Android Emulator
        run: |
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
      
          # Check if AVD exists before creating
          if ! $ANDROID_SDK_ROOT/emulator/emulator -list-avds | grep -q "TestEmulator"; then
            echo "AVD TestEmulator not found. Creating it now..."
            echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd --force -n TestEmulator -k "system-images;android-29;google_apis;x86" -d "pixel"
          fi
      
      - name: Start Android Emulator
        run: |
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
      
          # Start ADB
          adb start-server
      
          # Launch emulator in the background
          nohup $ANDROID_SDK_ROOT/emulator/emulator -avd TestEmulator -no-audio -no-window -gpu swiftshader_indirect -no-snapshot > emulator.log 2>&1 &
      
          # Wait for the emulator to boot
          for i in {1..240}; do
            if adb devices | grep "emulator-"; then
              echo "Emulator detected!"
              break
            fi
            echo "Waiting for emulator to boot..."
            sleep 5
          done
          adb wait-for-device


      - name: Install node_modules
        run: |
          npm install
    
      - name: Start RN Packager
        run: |
          npx react-native start &

      - name: Build app for Detox
        run: npm run detox-build

      - name: Run Detox tests
        run: npm run detox-test

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detox-artifacts
          path: artifacts
