name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Run Jest tests
      - name: Run Jest tests
        run: npm test

  detox-tests:
    runs-on: macos-latest # Required for iOS tests

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Build app for Detox
      - name: Build app for Detox
        run: npm run detox-build

      # Run Detox tests
      - name: Run Detox tests
        run: npm run detox-test